spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/mem:testdb
    username: root
    password:
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always
