spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: root
    password: "123"
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      keepAliveTime: 60000
      maxLifetime: 1800000
      maximumPoolSize: 5
      poolName: HikariCP-library
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

integration:
  openlibrary:
    baseUrl: "http://openlibrary.org"
  alfabank:
    baseUrl: "https://ibapi.alfabank.by:8273"
    connectTimeout: 10000
    readTimeout: 10000






